apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: troila.harbor.com:2443/devops/dev:v-bc98131
          imagePullPolicy: IfNotPresent
          name: web-app-java
      restartPolicy: Always
